Update airgap_input.txt
harness/helm-charts pull request #467
Opened 2023-11-16 11:33 UTC by iamtcreddy

2023-11-16 11:48 UTC, arya-harness requested changes

2023-11-16 11:48 UTC, arya-harness commented on src/modules/srm/Chart.yaml
> +- condition: global.cg.enabled
condition should global.ng.enabled

2023-11-16 11:51 UTC, iamtcreddy commented on src/modules/srm/Chart.yaml
> +- condition: global.cg.enabled
resolved

2023-11-16 11:53 UTC, arya-harness approved these changes
@swapnil-harness can you additionally approve this

2023-11-17 08:26 UTC, deepesh-ui approved these changes

2023-11-17 13:29 UTC, merged